source "https://rubygems.org"

gem "activerecord"
gem "dotenv"
gem "eventmachine"
gem "feed-normalizer"
gem "nokogiri"
gem "sanitize"
gem "slack-api"
gem "sqlite3"
gem "twitter"
gem "wikicloth"
gem "wikipedia-client"