 - じっけん大せいこう (2話「危機一髪!!」)
 - 人間を狂わすレコード、ジュラル星人の仕業に違いない！ (16話「殺人レコード恐怖のメロディ」)
 - よくも あんな キチガイレコードを！ (16話「殺人レコード恐怖のメロディ」)
 - １発でヨーロッパの半分が無くなる (23話「恐怖！精神病院」)
 - はいだらー！はいだらー！ (25話「雄一少年を救え!」)
 - 毎日ドゥンドゥンやろうじゃねぇか (25話「雄一少年を救え!」)
 - これから毎日家を焼こうぜ？ (25話「雄一少年を救え！」)
 - ごめんねー、僕のパパが君を車で轢いちゃってー (26話「記憶を無くした少女)
 - モチよ! (27話「燃える毒きのこの家」)
 - わぁ゛ぁ゛！ｷﾀｿﾞｰ！ (27話「燃える毒きのこの家」)
 - 地下で核爆発を起こさせているんDA☆ (34話「スカイロッド 地底に突っこめ！」)
 - ﾁｯﾁｯﾁｯﾁｯﾁ…そうか、頭の中に 爆弾が！ (35話「頭の中にダイナマイト」)
 - ボルガ博士、お許しください！ (35話「頭の中にダイナマイト」)
 - 可哀想なボルガ博士… (35話「頭の中にダイナマイト」)
 - 聞いたなコイツ！ (61話「バリカンの旧友が尋ねてきた」)